name: Validate Renovate Config

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"

permissions:
  {}

jobs:
  validate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-validate-renovate.yml@fae71ae9b9d9244639a89507641c6509f250c7b6 # v1
