name: Validate Renovate Config

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"

permissions:
  {}

jobs:
  validate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-validate-renovate.yml@44f126717d9c45856fbcff368eb87ce0f26773d3 # v1
